version: "3.3"
services:
  solr:
    domainname: ".org"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solr_search_engine
    volumes:
      - .:/opt/app
    working_dir: /etc/solr_home
    stdin_open: true
    expose:
      - 8983
    ports:
      - 8983:8983
    labels:
      name: solr_app
      type: seach_engine