version: "3.3"
services:
  solr:
    domainname: ".org"
    tty: true
    build:
      context: ./solr
      dockerfile: Dockerfile
    container_name: solr_search_engine
    volumes:
      - .:/opt/app/solr
    stdin_open: true
    restart: on-failure
    ports:
      - 8983:8983
    labels:
      name: solr_app
      type: seach_engine

  indexer:
    domainname: ".org"
    tty: true
    stdin_open: true
    hostname: solr
    build:
      context: ./../
      dockerfile: ./docker/indexer/Dockerfile
    container_name: indexer
    restart: on-failure
    labels:
      name: indexer
      type: search_engine

